# Generated by Django 5.0.7 on 2025-10-11 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_remove_bet_game_remove_bet_user_betrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betrecord',
            options={},
        ),
        migrations.AddField(
            model_name='betrecord',
            name='won_by',
            field=models.CharField(default='Player A', max_length=20),
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='status',
            field=models.CharField(choices=[('won', 'Won'), ('lost', 'Lost')], default='lost', max_length=10),
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
