# Generated by Django 5.0.7 on 2025-10-13 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_alter_betrecord_options_betrecord_won_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.BigIntegerField(db_index=True, unique=True)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('player_a_cards', models.JSONField()),
                ('player_b_cards', models.JSONField()),
                ('winner', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
