# Generated by Django 5.0.7 on 2025-10-13 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_roundhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item_type', models.CharField(choices=[('ENGINE', 'Engine Final'), ('BET', 'Place Bet')], db_index=True, max_length=10)),
                ('round_id', models.BigIntegerField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('player_a_cards', models.JSONField(blank=True, null=True)),
                ('player_b_cards', models.JSONField(blank=True, null=True)),
                ('official_winner', models.CharField(blank=True, max_length=1, null=True)),
                ('player_choice', models.CharField(blank=True, max_length=1, null=True)),
                ('bet_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('resolver', models.CharField(blank=True, max_length=12, null=True)),
                ('final_result', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RoundHistory',
        ),
    ]
