# Generated by Django 5.0.7 on 2025-10-13 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_roundfeed_delete_roundhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betrecord',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='roundfeed',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='prev_balance',
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='won_by',
        ),
        migrations.AddField(
            model_name='betrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betrecord',
            name='player',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='betrecord',
            name='round_id',
            field=models.CharField(db_index=True, default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='betrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roundfeed',
            name='bet_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='roundfeed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roundfeed',
            name='item_type',
            field=models.CharField(choices=[('Engine Final', 'Engine Final'), ('Place Bet', 'Place Bet')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roundfeed',
            name='resolver',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='roundfeed',
            name='round_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='roundfeed',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='roundfeed',
            index=models.Index(fields=['round_id'], name='bets_roundf_round_i_fbc8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='roundfeed',
            index=models.Index(fields=['item_type', 'created_at'], name='bets_roundf_item_ty_c8e4af_idx'),
        ),
    ]
