# Generated by Django 5.0.7 on 2025-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_alter_betrecord_options_alter_roundfeed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrecord',
            name='is_engine_generated',
            field=models.BooleanField(default=False),
        ),
    ]
