# Generated by Django 5.0.7 on 2025-10-13 18:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_betrecord_is_engine_generated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('A', 'Player A'), ('B', 'Player B')], max_length=1)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLACED', max_length=10)),
                ('payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('game', models.CharField(choices=[('tpt20', 'Teen Patti T20')], default='tpt20', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player_a_cards', models.JSONField(blank=True, null=True)),
                ('player_b_cards', models.JSONField(blank=True, null=True)),
                ('resolver', models.CharField(choices=[('official', 'Official'), ('biased', 'Biased')], default='official', max_length=16)),
                ('winner', models.CharField(blank=True, choices=[('A', 'Player A'), ('B', 'Player B')], max_length=1, null=True)),
                ('rake_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='betrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoundFeed',
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['game', 'created_at'], name='bets_round_game_a7cb7c_idx'),
        ),
        migrations.AddField(
            model_name='bet',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bets.round'),
        ),
        migrations.DeleteModel(
            name='BetRecord',
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'created_at'], name='bets_bet_user_id_06caac_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['round', 'status'], name='bets_bet_round_i_f0eb3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PLACED')), fields=('user', 'round', 'selection', 'stake', 'status'), name='uniq_open_bet_fingerprint'),
        ),
    ]
