# Generated by Django 5.0.7 on 2025-11-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_bet_round_remove_betrecord_user_delete_roundfeed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('value', models.BigIntegerField(default=0)),
            ],
        ),
    ]
