# Generated by Django 5.0.7 on 2025-10-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chip_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
