# Generated by Django 5.0.7 on 2025-10-18 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options_alter_user_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
